### Beaver Bus API example configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
      edu.oregonstate.mist.beaverbus.RideSystemsDAO: WARN
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/beaver-bus-api.log
      archivedLogFilenamePattern: logs/beaver-bus-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1/

httpClient:
  timeout: 150000ms
  connectionTimeout: 15000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 2
  maxConnectionsPerRoute: 2
  keepAlive: 0ms
  retries: 0
  userAgent: beaver-bus-api

rideSystems:
  baseURL: https://example.com/JSONPRelay.svc/
  apiKey: secret
